//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutcoldSolutions.GoogleMusic {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OutcoldSolutions.GoogleMusic.CoreResources", typeof(CoreResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user account has been deleted..
        /// </summary>
        internal static string Login_AccountDeleted {
            get {
                return ResourceManager.GetString("Login_AccountDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user account has been disabled..
        /// </summary>
        internal static string Login_AccountDisabled {
            get {
                return ResourceManager.GetString("Login_AccountDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login request used a username or password that is not recognized..
        /// </summary>
        internal static string Login_BadAuthentication {
            get {
                return ResourceManager.GetString("Login_BadAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A CAPTCHA is required..
        /// </summary>
        internal static string Login_CaptchaRequired {
            get {
                return ResourceManager.GetString("Login_CaptchaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account email address has not been verified. The user will need to access their Google account directly to resolve the issue before logging in using a non-Google application..
        /// </summary>
        internal static string Login_NotVerified {
            get {
                return ResourceManager.GetString("Login_NotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user&apos;s access to the specified service has been disabled..
        /// </summary>
        internal static string Login_ServiceDisabled {
            get {
                return ResourceManager.GetString("Login_ServiceDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service is not available; try again later..
        /// </summary>
        internal static string Login_ServiceUnavailable {
            get {
                return ResourceManager.GetString("Login_ServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has not agreed to terms. The user will need to access their Google account directly to resolve the issue before logging in using a non-Google application..
        /// </summary>
        internal static string Login_TermsNotAgreed {
            get {
                return ResourceManager.GetString("Login_TermsNotAgreed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The error is unknown or unspecified..
        /// </summary>
        internal static string Login_Unknown {
            get {
                return ResourceManager.GetString("Login_Unknown", resourceCulture);
            }
        }
    }
}
